# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: adca83465b153c3c1332b42cacefb0a7f3c7e99aec67e409585ff19645b83843274ad7abdab23bb1898f59071a502e2b2b5d455ea4723bbf7df5847e5bfbe1f2

test:
  secret_key_base: c4ece079ce2bb35fe0a3ea89860aca5daf703a1b12e03534d8da39a7309ea849789ca078f4f6bac262f36c58c897040f8a96f4c4bdcbcc56832d9d1022754177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
